### ISSUE TITLE
GravityForms widget is complaining in the logs

### ISSUE THREAD

**Issue by cgsmith** [johnjamesjacoby/easttroyweb.com#13]
Something is causing the logs to complain with GF.

```
2016/08/11 06:51:31 [error] 7536#7536: *13269 FastCGI sent in stderr: "PHP message: WordPress database error Duplicate entry '0' for key 'PRIMARY' for query INSERT INTO wp_16_rg_form_view(form_id, date_created, ip) values(1, utc_timestamp(), '') made by require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), include('/themes/genesis/404.php'), genesis, do_action('genesis_after_content'), genesis_get_sidebar, get_sidebar, locate_template, load_template, require_once('/themes/genesis/sidebar.php'), do_action('genesis_sidebar'), genesis_do_sidebar, dynamic_sidebar, WP_Widget->display_callback, GFWidget->widget, GFForms::get_form, GFFormDisplay::get_form, GFFormsModel::insert_form_view" while reading upstream, client: , server: domain.com, request: "GET // HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "domain.com"
```

**Comment by JJJ** [comment]
I'll check the logs and report back.

**Comment by JJJ** [comment]
2 sites that were imported had the following issues:
- Imported as MyIASM vs InnoDB
- Missing `AUTO_INCREMENT` on Gravity Forms tables

Solution:
- Set `sql_mode=NO_ENGINE_SUBSTITUTION` in `mysql.cnf` (to avoid empty datetime errors)
- Restart MySQL
- Convert all tables to InnoDB
- Walk through tables & compare them to their anticipated schema's
- `ALTER` any tables with missing `AUTO_INCREMENT` values
- Unset `sql_mode=NO_ENGINE_SUBSTITUTION` in `mysql.cnf`
- Restart MySQL

2 hours worth of hunting & fixing <3
